apiVersion: apps/v1
kind: Deployment
metadata:
  name: carma-api
  labels:
    app: carma-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carma-api
  template:
    metadata:
      labels:
        app: carma-api
    spec:
      containers:
      - name: carma-api
        image: akscontainerregistry1234.azurecr.io/carma_main-api:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: carma-api
spec:
  type: ClusterIP
  selector:
    app: carma-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80